import { getModelWithMeta } from "../config/llmModels.js";
import { generatePdf } from "../utils/generatePdf.js";
import { saveFileAndGetUrl } from "../utils/fileStorage.js";
import { deductCredits } from "../utils/deductCredits.js";
import { checkAgentLimit } from "../config/agentLimit.js";
import { invokeWithTracking } from "../observability/usageTracker.js";

const parseJsonSafely = (text, fallbackTopic) => {
  try {
    const raw = Array.isArray(text) ? text.map((c) => c?.text || "").join("\n") : String(text || "");
    const cleaned = raw.replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/```\s*$/i, "").trim();

    if (cleaned.startsWith("{") && cleaned.endsWith("}")) {
      return JSON.parse(cleaned);
    }

    const jsonMatch = cleaned.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      return JSON.parse(jsonMatch[0]);
    }
  } catch (e) {
    console.warn("[PDF Agent] Failed to parse structured JSON from LLM output, building fallback structure:", e.message);
  }

  return {
    title: fallbackTopic.length > 40 ? `${fallbackTopic.substring(0, 37)}...` : fallbackTopic,
    subtitle: "Generated by CortexAI",
    sections: [
      {
        heading: "Overview & Summary",
        points: [
          `Document prepared for: ${fallbackTopic}`,
          "Detailed breakdown generated via CortexAI document synthesis.",
          "Comprehensive multi-perspective analysis and key takeaways."
        ]
      }
    ]
  };
};

export const pdfAgent = async (state) => {
  try {
    if (state.userId) {
      await checkAgentLimit(state.userId, "pdf");
    }

    const { llm, modelName } = await getModelWithMeta("pdf");
    const prompt = `You are an expert document writer.
Return ONLY valid JSON without markdown fences or introduction.

Structure:
{
  "title": "Document Title",
  "subtitle": "Document Subtitle",
  "sections": [
    {
      "heading": "Section Heading",
      "points": [
        "Concise, informative point 1",
        "Concise, informative point 2",
        "Concise, informative point 3"
      ]
    }
  ]
}

Generate 4-6 detailed sections with 3-5 high quality bullet points each for this topic:
${state.prompt}`;

    const { response, usage } = await invokeWithTracking(llm, prompt, modelName, "pdfAgent");
    const data = parseJsonSafely(response?.content, state.prompt);

    if (state.userId) {
      await deductCredits(state.userId, "pdf");
    }

    const pdfBuffer = await generatePdf(data);
    const filename = `pdf-${Date.now()}.pdf`;
    const downloadUrl = await saveFileAndGetUrl(filename, pdfBuffer, "application/pdf");

    return {
      ...state,
      metrics: {
        ...(state.metrics || {}),
        tokens: usage?.totalTokens || null
      },
      aiResponse: `# 📄 PDF Document Generated

**${data.title}**  
*${data.subtitle || "Prepared by CortexAI"}*

---

### Key Sections:
${data.sections.map((s) => `* **${s.heading}** (${s.points?.length || 0} points)`).join("\n")}

---

📥 **[Download PDF Document](${downloadUrl})**  
*Click the link above to view or download your formatted PDF document.*`
    };
  } catch (error) {
    console.error("[PDF Agent Error]", error);
    return {
      ...state,
      aiResponse: `⚠️ PDF generation encountered an error: ${error.message || "Failed to generate document"}. Please try again.`
    };
  }
};