import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
  const title = data?.title || "Document";
  const subtitle = data?.subtitle || "";
  const sections = Array.isArray(data?.sections) && data.sections.length > 0
    ? data.sections
    : [{ heading: "Summary", points: ["No sections provided."] }];

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 50,
        info: {
          Author: "CortexAI",
          Title: title,
          Creator: "CortexAI"
        }
      });

      const chunks = [];
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", (err) => reject(err));

      // Document Title
      doc
        .fontSize(24)
        .fillColor("#111827")
        .text(title, { align: "center" });

      if (subtitle) {
        doc.moveDown(0.5);
        doc
          .fontSize(13)
          .fillColor("#6B7280")
          .text(subtitle, { align: "center" });
      }

      doc.moveDown(1.5);

      // Render each section
      sections.forEach((s) => {
        if (s.heading) {
          doc
            .fontSize(16)
            .fillColor("#1E3A8A")
            .text(s.heading);
          doc.moveDown(0.4);
        }

        if (Array.isArray(s.points)) {
          s.points.forEach((p) => {
            doc
              .fontSize(11)
              .fillColor("#374151")
              .text(`•  ${p}`, { lineGap: 4 });
          });
        }
        doc.moveDown(0.8);
      });

      // Footer
      doc.moveDown(1);
      doc
        .fontSize(9)
        .fillColor("#9CA3AF")
        .text("Generated by CortexAI — Adaptive Multi-Agent Platform", { align: "center" });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
